### ISSUE TITLE
Use `Unit -> a` instead of a getter field?

### ISSUE THREAD

**Issue by natefaubion** [ajnsit/purescript-supply#1]
What is the motivation for using a getter? Could you achieve the same result by yielding `Unit -> a` instead of `{ val :: a }`, where `val` is esentially a `Unit -> a` getter. I'm not sure it's safe to type this as a `Record`, when it has a getter and an instance value that is otherwise not part of the record type.

**Comment by natefaubion** [comment]
FWIW, if it was `Unit -> a` or `Lazy a` you would not need any FFI.

**Comment by ajnsit** [comment]
@natefaubion yes you are right! I actually started with an implementation of `unsafeInterleaveEffect` and implemented this lib as an example. I entirely missed that lazy values fit perfectly here. I have removed the FFI and moved to a `Unit -> a` approach.

**Comment by ajnsit** [comment]
I just realised that my lazy implementation breaks referential transparency. `supplyValue :: Supply a -> a` will not return the same value for the same supply. Reopening for now.

**Comment by natefaubion** [comment]
I think the signature would be something like:
```purescript
unsafeInterleaveEffect :: forall a. Effect a -> Effect (Lazy a)
unsafeInterleaveEffect eff = pure $ Lazy.defer \_ -> unsafePerformEffect eff

data Supply a = Supply (Lazy a) (Lazy (Supply a)) (Lazy (Supply a))

supplyValue :: forall a. Supply a -> a
supplyValue (Supply a _ _) = Lazy.force a
```

**Comment by natefaubion** [comment]
Oh hah, I see that your commit is what I put above. It isn't clear to me how that's different than what you've already implemented though. You getter approach is equivalent to `Lazy`, afaict.

**Comment by ajnsit** [comment]
My JS code was basically caching the value so that the same value is returned every time.
It would look something like this without using FFI -

```purescript
unsafeInterleaveEffect :: forall a. Effect a -> Effect (Unit -> a)
unsafeInterleaveEffect m = do
  r <- Ref.new Nothing
  pure \_ -> unsafePerformEffect do
    v <- Ref.read r
    case v of
      Nothing -> do
        res <- m
        Ref.write (Just res) r
        pure res
      Just res -> pure res
```

**Comment by natefaubion** [comment]
Yes, that's effectively the implementation of `Lazy`, though Lazy uses a mutable JS closure.

**Comment by ajnsit** [comment]
Oh I see, I didn't know that. I'll pull in `purescript-lazy` as a dependency then.

**Comment by ajnsit** [comment]
All right, I reimplemented the library in terms of `purescript-lazy`. Thanks for the suggestion @natefaubion!
